import Head from 'next/head';
import Image from 'next/image';
import { useMemo } from 'react';
import { useTheme } from 'next-themes';

import { ThemeType } from '~/types';

const ITEMS = [
	{
		title: <>Documentation &rarr;</>,
		description: 'Find in-depth information about Next.js features and API.',
		href: 'https://nextjs.org/docs',
	},
	{
		title: <>Learn &rarr;</>,
		description: 'Learn about Next.js in an interactive course with quizzes!',
		href: 'https://nextjs.org/learn',
	},
	{
		title: <>Examples &rarr;</>,
		description: 'Discover and deploy boilerplate example Next.js projects.',
		href: 'https://github.com/vercel/next.js/tree/master/examples',
	},
	{
		title: <>Deploy &rarr;</>,
		description: 'Instantly deploy your Next.js site to a public URL with Vercel.',
		href: 'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
	},
];

export default function Home() {
	const { theme, setTheme } = useTheme();

	const isDark = useMemo(() => {
		if (theme === ThemeType.SYSTEM) {
			return window.matchMedia('(prefers-color-scheme: dark)').matches;
		}

		return theme === ThemeType.DARK;
	}, [theme]);

	return (
		<>
			<Head>
				<title>Nextwind</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="min-h-screen flex flex-1 flex-col items-center justify-center py-16">
				<h1 className="m-0 leading-5 text-3xl sm:text-5xl lg:text-7xl font-bold text-center">
					Welcome to{' '}
					<a
						className="text-blue-500 no-underline rounded-md default-transition default-focus"
						href="https://nextjs.org"
					>
						Next.js!
					</a>
				</h1>

				<p className="my-8 leading-5 text-2xl text-center">
					Get started by editing{' '}
					<code className="px-2 py-1 bg-gray-100 dark:bg-gray-800 rounded text-lg">
						pages/index.tsx
					</code>
				</p>

				<div className="w-full flex items-center justify-center p-4">
					<button
						aria-label="Toggle Theme"
						className="w-full sm:w-auto px-8 py-3 border-2 border-gray-200 dark:border-gray-800 hover:(text-blue-500 !border-blue-500) rounded-md font-bold leading-6 transition ease-in-out duration-500 default-focus"
						onClick={() => setTheme(isDark ? 'light' : 'dark')}
						type="submit"
					>
						<svg
							xmlns="http://www.w3.org/2000/svg"
							width="24"
							height="24"
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							strokeWidth="2"
							strokeLinecap="round"
							strokeLinejoin="round"
							className="inline-flex mr-3"
						>
							{isDark ? (
								<>
									<circle cx="12" cy="12" r="5"></circle>
									<line x1="12" y1="1" x2="12" y2="3"></line>
									<line x1="12" y1="21" x2="12" y2="23"></line>
									<line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line>
									<line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line>
									<line x1="1" y1="12" x2="3" y2="12"></line>
									<line x1="21" y1="12" x2="23" y2="12"></line>
									<line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line>
									<line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line>
								</>
							) : (
								<path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
							)}
						</svg>
						{isDark ? 'Light' : 'Dark'} Theme
					</button>
				</div>

				<div className="flex flex-wrap items-center justify-center max-w-sm md:max-w-4xl md:w-full">
					{ITEMS.map(({ title, description, href }, i) => (
						<a
							className="max-w-sm space-y-2 m-4 p-6 text-left no-underline border-2 border-gray-200 dark:border-gray-800 hover:(text-blue-500 !border-blue-500) rounded-md default-transition default-focus"
							href={href}
							key={i}
						>
							<h2 className="text-2xl font-bold">{title}</h2>
							<p className="text-gray-400 text-xl leading-6">{description}</p>
						</a>
					))}
				</div>
			</main>

			<footer className="flex items-center justify-center py-8 border-t-2 border-gray-200 dark:border-gray-800">
				<a
					className="flex flex-grow items-center justify-center"
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					rel="noopener noreferrer"
					target="_blank"
				>
					Powered by{' '}
					<span className="h-4 ml-0.5">
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</>
	);
}
