import Head from 'next/head';
import Image from 'next/image';

const ITEMS = [
	{
		title: <>Documentation &rarr;</>,
		description: 'Find in-depth information about Next.js features and API.',
		href: 'https://nextjs.org/docs',
	},
	{
		title: <>Learn &rarr;</>,
		description: 'Learn about Next.js in an interactive course with quizzes!',
		href: 'https://nextjs.org/learn',
	},
	{
		title: <>Examples &rarr;</>,
		description: 'Discover and deploy boilerplate example Next.js projects.',
		href: 'https://github.com/vercel/next.js/tree/master/examples',
	},
	{
		title: <>Deploy &rarr;</>,
		description: 'Instantly deploy your Next.js site to a public URL with Vercel.',
		href: 'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
	},
];

export default function Home() {
	return (
		<>
			<Head>
				<title>Nextwind</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="min-h-screen flex flex-1 flex-col items-center justify-center py-16">
				<h1 className="m-0 leading-5 text-3xl sm:text-5xl lg:text-7xl font-bold text-center">
					Welcome to{' '}
					<a
						className="text-blue-500 no-underline rounded-md transition ease-in-out duration-300 focus:(outline-none ring-4 ring-offset-4 ring-blue-500)"
						href="https://nextjs.org">
						Next.js!
					</a>
				</h1>

				<p className="my-8 leading-5 text-2xl text-center">
					Get started by editing{' '}
					<code className="px-2 py-1 bg-gray-100 dark:bg-gray-800 rounded text-lg">
						pages/index.tsx
					</code>
				</p>

				<div className="flex flex-wrap items-center justify-center max-w-sm md:max-w-4xl md:w-full">
					{ITEMS.map(({ title, description, href }, i) => (
						<a
							className="max-w-sm space-y-2 m-4 p-6 text-left no-underline border-2 border-gray-300 dark:border-gray-800 hover:(text-blue-500 !border-blue-500) rounded-md transition ease-in-out duration-300 focus:(outline-none ring-4 ring-offset-4 ring-blue-500)"
							href={href}
							key={i}>
							<h2 className="text-2xl font-bold">{title}</h2>
							<p className="text-gray-400 text-xl leading-6">{description}</p>
						</a>
					))}
				</div>
			</main>

			<footer className="flex items-center justify-center py-8 border-t-2 border-gray-300 dark:border-gray-800">
				<a
					className="flex flex-grow items-center justify-center"
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					rel="noopener noreferrer"
					target="_blank">
					Powered by{' '}
					<span className="h-4 ml-0.5">
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</>
	);
}
